#!/bin/bash

save_location=~/.config/.hypr_cache/temp

function checkENVDir() {
    if ! test -d "$save_location"; then
        mkdir -p $save_location
    fi
    if ! test -f "$save_location/$1"; then
        touch $save_location/$1
    fi
}

