local map = require'utils'.map

-- :Gedit will always send us back to the working copy
-- and thus serves as a quasi back button
-- map('n', '<leader>gg', '<Esc>:Gedit<CR>', {noremap = true})
-- map('n', '<leader>gs', '<Esc>:Git<CR>', {noremap = true})
-- map('n', '<leader>gr', '<Esc>:Gread<CR>', {noremap = true})
-- map('n', '<leader>gw', '<Esc>:Gwrite<CR>', {noremap = true})
-- map('n', '<leader>ga', '<Esc>:Git add %<CR>', {noremap = true})
-- map('n', '<leader>gA', '<Esc>:Git add .<CR>', {noremap = true})
-- map('n', '<leader>gb', '<Esc>:Git blame<CR>', {noremap = true})
-- -- map('', '<leader>gc', '<Esc>:Git commit<CR>',     { noremap = true })
--
-- map('n', '<leader>gd', '<Esc>:Gvdiffsplit!<CR>', {noremap = true})
--
-- map('n', '<leader>gD',
--     '<Esc>:Git diff | setlocal nonumber norelativenumber | wincmd o<CR>',
--     {noremap = true})
-- map('n', '<leader>gp', '<Esc>:Git push<CR>', {noremap = true})
-- map('n', '<leader>gS', '<Esc>:Git stash -- %<CR>', {noremap = true})
-- map('n', '<leader>g-', '<Esc>:Git stash<CR>', {noremap = true})
-- map('n', '<leader>g+', '<Esc>:Git stash pop<CR>', {noremap = true})
-- map('n', '<leader>gf', '<Esc>:Git fetch --all<CR>', {noremap = true})
-- map('n', '<leader>gF', '<Esc>:Git fetch origin<CR>', {noremap = true})
-- map('n', '<leader>gl', '<Esc>:Git log --stat %<CR>', {noremap = true})
-- map('n', '<leader>gL', '<Esc>:Git log --stat -n 100<CR>', {noremap = true})
-- map('n', '<leader>ge', '<Esc>:vsp<CR>:Gedit HEAD~:%<left><left>',
--     {noremap = true})
-- map('n', '<leader>gE', '<Esc>:sp<CR>:Gedit HEAD~:%<left><left>',
--     {noremap = true})
